# Configuration file for Sphinx documentation
# AUTO-GENERATED by Introligo from introligo_config.yaml
#
# WARNING: This file is AUTO-GENERATED and should NOT be edited manually.
# Any manual changes will be OVERWRITTEN when regenerated.
#
# To modify Sphinx configuration:
# 1. Edit your introligo YAML configuration file
# 2. Regenerate using: python -m introligo <config.yaml> -o <output_dir>

from __future__ import annotations

from pathlib import Path

# -- Paths --------------------------------------------------------------------
DOCS_DIR = Path(__file__).resolve().parent

PROJECT_ROOT = DOCS_DIR.parent


# -- Project information -------------------------------------------------------
project = "Example System"
author = "Example Project Team"

copyright = "2025, Example Project Team"


release = "2.0.0"


version = "2.0"


# -- General configuration -----------------------------------------------------
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = []
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]


# -- HTML output options -------------------------------------------------------
html_theme = "alabaster"


html_title = "Example System Documentation"


html_theme_options = {
    "description": "Modern system with comprehensive API",
    "github_user": "example",
    "github_repo": "example-system",
}
