name: Lint

on:
  push:
    branches:
      - master
      - main
      - dev/**
  pull_request:
    branches:
      - master
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff mypy types-PyYAML
        pip install -e .

    - name: Run Ruff linter
      run: |
        ruff check .

    - name: Run Ruff formatter check
      run: |
        ruff format --check .

    - name: Run mypy type checker
      run: |
        mypy introligo
      continue-on-error: true
